INSERT INTO USERS(ID, NAME, EMAIL) VALUES (1, '문재인', 'moon@daou.com');
INSERT INTO USERS(ID, NAME, EMAIL) VALUES (2, '김정은', 'kim@daou.com');
INSERT INTO USERS(ID, NAME, EMAIL) VALUES (3, '트럼프', 't@daou.com');
INSERT INTO USERS(ID, NAME, EMAIL) VALUES (4, '시진핑', 'xi@daou.com');

INSERT INTO USER_ADDRESS(ID, COUNTRY, ADDRESS, USERS_ID) VALUES (1, '한국', '서울', 1);
INSERT INTO USER_ADDRESS(ID, COUNTRY, ADDRESS, USERS_ID) VALUES (2, '북한', '평양', 2);
